config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
    
  get "documents/query"

  get "documents/index"

  get "documents/create"
  
  get "documents/show"
  
  resources :documents
  
  resources :users, only: [:update]
  
  get 'about' => 'welcome#about'
  
  get 'contact' => 'welcome#contact'
  
  get 'search' => 'documents#search'
  
  get 'Raven' => 'welcome#index'
  
  root to: 'welcome#index'
  
end

app/models/action.rb
class Action < ActiveRecord::Base
  belongs_to :relation
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :document, touch: true
end

app/models/document.rb
class Document < ActiveRecord::Base
#    belongs_to :user, touch: true
    has_many :keywords, as: :keywordable
    has_many :entities, as: :entityable
    has_many :concepts
    has_many :relations
    has_one :sentiment, as: :sentimentable

    

    default_scope { order('created_at DESC') }
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  belongs_to :entityable, polymorphic: true
  belongs_to :document, touch: true
  has_one :sentiment, as: :sentimentable
 end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :document, touch: true
  belongs_to :keywordable, polymorphic: true
  has_one :sentiment, as: :sentimentable
  
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :document, touch: true
  has_many :actions
  has_many :relation_objects
  has_many :keywords, as: :keywordable
  has_many :entities, as: :entityable
end

app/models/relation_object.rb
class RelationObject < ActiveRecord::Base
  belongs_to :relation
  has_one :sentiment, as: :sentimentable
  has_many :keywords, as: :keywordable
  has_many :entities, as: :entityable
  
end

app/models/sentiment.rb
class Sentiment < ActiveRecord::Base
  belongs_to :sentimentable, polymorphic: true
  belongs_to :relation_object
  belongs_to :document
  belongs_to :entity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  

  has_many :documents


end

app/controllers/alchemy_controller.rb
require 'alchemyapi_ruby/alchemyapi'
require 'json'

class AlchemyController < ApplicationController
  before_action :authenticate_user!

  def index
    #@document = Document.find(params[:id])
    @documents = Document.all
    @concepts = Concept.all
    @entities = Entity.all
    @keywords = Keyword.all 
    @relations = Relation.all 
    @relation_objects = RelationObject.all 
    @sentiments = Sentiment.all 
  end
  
  def show 
    @document = Document.find(params[:id])
  end
 
  def create
    alchemy_api_parser = AlchemyapiParser.new(params, current_user)
    alchemy_api_parser.call

    if alchemy_api_parser.successful?
      flash[:notice] = "Input was successfully analyzed and persisted."
      redirect_to alchemy_index_path
    else
      flash[:error] = "There was a problem analyzing your input. Please try again."
      redirect_to alchemy_index_path
    end
  end
    
  def destroy
     @document = Document.find(params[:id])
 
    if @document.destroy
      flash[:notice] = "\"#{@document.id}\" was deleted successfully."
      redirect_to alchemy_index_path
    else
      flash[:error] = "There was an error deleting this result."
      redirect_to alchemy_index_path
     end
   end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end

   helper_method :current_user
end

app/controllers/documents_controller.rb
require 'alchemyapi_ruby/alchemyapi'
require 'json'

class DocumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @documents = Document.all
  end
  
  def show
    @document = Document.find(params[:id])
    @concepts = @document.concepts
    @entities = @document.entities
    @keywords = @document.keywords
    @relations = @document.relations
  end
  
  def create
    alchemy_api_parser = AlchemyapiParser.new(params, current_user)
    alchemy_api_parser.call

    if alchemy_api_parser.successful?
      flash[:notice] = "Input was successfully analyzed and persisted."
    else
      flash[:error] = "There was a problem analyzing your input. Please try again."
    end
    redirect_to documents_index_path
  end
    
  def destroy
     @document = Document.find(params[:id])
 
    if @document.destroy
      flash[:notice] = "\"#{@document.id}\" was deleted successfully."
      redirect_to documents_index_path
    else
      flash[:error] = "There was an error deleting this result."
      redirect_to documents_index_path
     end
   end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name, :avatar)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def analyze
  end
  
  def show 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/search_helper copy 2.rb
module SearchHelper
end

app/helpers/search_helper copy.rb
module SearchHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alchemy/index.html.erb
<h2>Data Store Totals</h2>
<p><b>Total Alchemy API points consumed:</b> <%= Document.sum(:transaction_count) %></p>
<p><b>Number of document analysis returns:</b> <%= Document.count %></p>

<h2>Analysis Results</h2>
<% @documents.each do |document| %>
<p><b>Title: </b> <%= link_to document.title, @document %></p>
  <p><b>Author: </b> <%= document.author %></p>
  <p><b>URL: </b> <%= document.url %></p>
	<p><b>Date Retrieved:</b> <%= document.created_at %></p>
  <p><b>Sentiment type: </b> <%= document.sentiment.sentiment_type %></p>
  <p><b>Sentiment score: </b> <%= document.sentiment.sentiment_score %></p>
<HR>
<% end %>

app/views/alchemy/search.html.erb
<h2>Content Analysis</h2>


</br>
<%= form_tag("alchemy/create", method: "get") do %>
	
	<%= label_tag('type', "Choose your input type:") %>
</br>
	<%=  radio_button_tag(:type, "text")  %> 
	&thinsp;
	<%=  label_tag(:text_input, "text")  %>
	&emsp;
	<%=  radio_button_tag(:type, "url")  %>
	&thinsp;
	<%=  label_tag(:url_input, "url")  %>
	
</br>
</br>

	<%= label_tag(:q, "Perform Analysis:") %>
</br>
	<%= search_field_tag :q, value = nil, options = {style:"width:250px;border-radius:5px;padding-bottom:5px;"} %>
</br>
</br>
	<%= submit_tag("Analyze") %>

<% end %>

app/views/alchemy/show.html.erb
<div>
  <h3
  </br>
  <p><b>Title: </b> <%= @document.title %></p>
  <p><b>Author: </b> <%= @document.author %></p>
  <p><b>Source: </b> <%= @document.url %></p>
  <p><b>Sentiment type: </b> <%= @document.sentiment.sentiment_type %></p>
  <p><b>Sentiment score: </b> <%= @document.sentiment.sentiment_score %></p>
  <p><b>Full text: </b> <%= @document.document_text %></p>
</div>

app/views/documents/_document.html.erb
<% @documents.each do |doc| %>
<h2><%= link_to document.id, document %></h2>
<p><i><%= friendly_date document.created_at %></li></p>
<p><%= document.result %></p>
<p>
	<%= link_to 'Delete', document, method: :delete,
	data: { confirm: 'Are you sure?' } %>
</p>
<% end %>

app/views/documents/index.html.erb
<h2>Data Store Totals</h2>
<!-- <p><b>Total Alchemy API points consumed:</b> Document.sum(:transaction_count) </p> -->	
<p><b>Number of document analysis returns:</b> <%= Document.count %></p>

<h2>Analysis Results</h2>
<% @documents.each do |document| %>
  <p><b>Title: </b> <%= link_to document.title, document %></p>
  <p><b>Author: </b> <%= document.author %></p>
  <p><b>URL: </b> <%= document.url %></p>
	<p><b>Date Retrieved:</b> <%= document.created_at %></p>
<HR>
<% end %>

app/views/documents/search.html.erb
<h2>Content Analysis</h2>

</br>
<%= form_tag("documents/create", method: "get") do %>
	<%= label_tag('type', "Choose your input type:") %>
  </br>

  <div id="text"><%=  radio_button_tag(:type, "text")  %> 
	
    <%=  label_tag(:text_input, "text")  %></div>

	<div id="url"><%=  radio_button_tag(:type, "url")  %>
	
    <%=  label_tag(:url_input, "url")  %></div>
 
  <div id="file"><%=  radio_button_tag(:type, "text")  %>
	
    <%=  label_tag(:file_input, "file")  %></div>
  	
  </br>

  <div id="file_browse"><input type="file" name="inputfile"></div>

  </br>

  <div class="search_field"><%= label_tag(:q, "Perform Analysis:") %></div>
  </br>

  <div class="search_field"><%= search_field_tag :q, value = nil, options = {style:"width:400px;border-radius:5px;padding-bottom:5px;"} %>  
  <%= submit_tag("Analyze") %></div>

<% end %>

app/views/documents/show.html.erb
<div>
  </br>
  <%= link_to "<< Results", documents_path %>
  <h2><%= @document.title %></h2>
  <p>Author:  <%= @document.author %></p>
  <p>Source:  <%= @document.url %></p>
  <p>Sentiment type:  <%= @document.sentiment.sentiment_type %></p>
  <p>Sentiment score:  <%= @document.sentiment.sentiment_score %></p>
  <%= link_to "Delete this document", @document, method: :delete, data: {confirm: "Are you sure?"} %>
  
<HR>
  <h2>Entities: </h2>  
  <%= @entities.each do |entity| %>
    <p>Entity: <%= entity.text %></p>
    <p>Count: <%= entity.count %></p>
    <p>Type: <%= entity.entity_type %></p>
    <p>Relevance: <%= entity.relevance %></p>
    <p>Knowledge Graph: <%= entity.knowledge_graph_type_hierarchy %></p>
    <p>Sentiment: <%= entity.sentiment.sentiment_type %></p>
    <p>Sentiment Score: <%= entity.sentiment.sentiment_score %></p>
    <p>Sentiment Mixed: <%= entity.sentiment.sentiment_mixed %></p>
  <HR>
  <% end %>
  <HR>
  <h2>Keywords: </h2>  
  <%= @keywords.each do |keyword| %>
    <p>Keyword: <%= keyword.text %></p>
    <p>Type: <%= keyword.keywordable_type %></p>
    <p>Relevance: <%= keyword.relevance %></p>
    <p>Knowledge Graph: <%= keyword.knowledge_graph_type_hierarchy %></p>
    <p>Sentiment: <%= keyword.sentiment.sentiment_type %></p>
    <p>Sentiment Score: <%= keyword.sentiment.sentiment_score %></p>
    <p>Sentiment Mixed: <%= keyword.sentiment.sentiment_mixed %></p>
  <HR>
  <% end %>
  <HR>
  <h2>Concepts: </h2>  
  <%= @concepts.each do |concept| %>
    <p>Concept: <%= concept.text %></p>
    <p>Relevance: <%= concept.relevance %></p>
    <p>Knowledge Graph: <%= concept.knowledge_graph_type_hierarchy %></p>
  <HR>
  <% end %>    
  <HR>
    <h2>Relations: </h2>  
    <%= @relations.each do |relation| %>
    <p>Extracted Sentence: <%= relation.sentence %></p>
    <p>Subject: <%= relation.subject_text %></p>
    <!--put relation loops here (keyword, entity, action, relation object)-->
      <p>Verb Normalization: </p>
      <%= relation.actions.each do |action| %>
   
        <p>Action: <%= action.text %> </p>
        <p>Lemmatized: <%= action.lemmatized %> </p>
        <p>Verb: <%= action.verb_text %> </p>
        <p>Tense: <%= action.verb_tense %> </p>
      <% end %>
      <%= relation.relation_objects.each do |object| %>
        <p>Object Text:  <%= object.text %> </p>
      <% end %>
    <p>Relational Entities: </p>
    <%= relation.entities.each do |entity| %>
      <p>Entity: <%= entity.text %></p>
      <p>Type: <%= entity.entity_type %></p>
    <% end %>
  <HR>
  <% end %>    
  <HR>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Raven</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul class="nav nav-tabs">
      <li><%= link_to "Raven", root_path %></li>
    <% if current_user %>
    <li><%= link_to "Analyze", search_path %></li>
    <li><%= link_to "Results", documents_path %></li>
    <% end %>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Contact", contact_path %></li>
    
    <div class="pull-right user-info">
           <% if current_user %>
           
              Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>

           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
  </ul>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Raven</h1>
</br>
<p>Raven is a text analytics application that allows small businesses to take advantage of the power unstructured data on the web.</p>
</br>
<p>Raven was developed by Joel Ramsey, co-founder of Glyphex Technologies, Limited.</p>

app/views/welcome/analyze.html.erb
<h1>Welcome#analyze</h1>
<p>Find me in app/views/welcome/analyze.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Contact Glyphex Technologies, Limited</h1>
  <p>General Inquiries</p>
    
      <p><a href="mailto:support@glyphex.com"><i class='glyphicon glyphicon-wrench'></i> Product Support</a></p>
      <p><a href="msilto:info@glyphex.com"><i class='glyphicon glyphicon-bullhorn'></i> Information</a></p>
    

  <p>Joel Ramsey - Co-founder</p>
   
      <p><a href="mailto:joel.d.ramsey@gmail.com"><i class='glyphicon glyphicon-envelope'></i> Email Joel</a></p>
      
    

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Raven</h1>
  </br>
  <p>Raven is a user-friendly text analytics platform for small businesses that delivers high-end data services without the associated price tag!</p>
  
</div>